name: docs
channels:
- conda-forge
- opensim-org
- default
dependencies:
- python==3.9
- opensim=4.4=py39np120
- btk
- scipy
- matplotlib
- pandas
- enum34
- configparser
- pytest
- pytest-mpl
- scikit-learn
- beautifulsoup4 
- pyyaml
- yamlordereddictloader
- xlrd
- openpyxl
- xlwt
- lxml
- pip
- myst-parser
- sphinx
- sphinx-argparse
- sphinxcontrib-mermaid
- pydata-sphinx-theme
